#pragma kernel CSMain

float alphaCutoff;
float smoothFactor;

float4 color;

uint2 texSize;
RWTexture2D<float4> tex;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	if (id.x >= texSize.x || id.y >= texSize.y)
		return;

	float a = smoothstep(alphaCutoff - smoothFactor, alphaCutoff + smoothFactor, tex[id.xy].a);

	tex[id.xy] = float4(color.x, color.y, color.z, color.a * a);
}
